version: "3.8"
services:
  db:
    image: postgres:15
    container_name: healthtracker_db
    restart: always
    environment:
      POSTGRES_USER: healthuser
      POSTGRES_PASSWORD: healthpass
      POSTGRES_DB: healthtracker
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data